#!/usr/bin/python

from turtle import *

colormode(255)

endermangrey = [22, 22, 22]

pencolor(endermangrey)

forward(200)

left(90)

forward(200)

right(90)

forward(100)

left(90)

forward(200)

left(90)

forward(100)

left(90)

forward(100)

right(90)

forward(100

left(90)

forward(100)

right(90)

forward(200)

right(90)

forward(100)

left(90)

forward(100)

right(90)

forward(100)